// World-Class Video Aggregation Types
export interface WorldClassVideo {
  id: string;
  title: string;
  description: string;
  aiSummary: string;
  platform: 'youtube' | 'tiktok' | 'instagram' | 'facebook' | 'x-twitter' | 'twitch' | 'local' | 'live';
  platformName: string;
  category: string;
  tags: string[];
  duration: string;
  durationSeconds: number;
  views: number;
  likes: number;
  dislikes?: number;
  comments: number;
  shares: number;
  saves: number;
  thumbnail: string;
  thumbnailHd?: string;
  videoUrl?: string;
  embedUrl?: string;
  streamUrl?: string;
  isLive: boolean;
  isStreamable: boolean;
  
  // Author information
  author: {
    id: string;
    name: string;
    username?: string;
    avatar: string;
    verified: boolean;
    followers: number;
    subscriberCount?: number;
    isOfficial?: boolean;
    badges: string[];
  };

  // AI & Analytics
  aiConfidence: number;
  sentiment: 'positive' | 'neutral' | 'negative' | 'mixed';
  sentimentScore: number;
  topics: string[];
  keywords: string[];
  transcription?: string;
  captions?: VideoCaption[];
  
  // Engagement metrics
  engagementRate: number;
  watchTimeMinutes: number;
  averageWatchTime: number;
  clickThroughRate?: number;
  
  // Metadata
  uploadDate: Date;
  publishedAt: Date;
  lastUpdated: Date;
  language: string;
  location?: {
    country: string;
    city?: string;
    coordinates?: [number, number];
  };
  
  // Live streaming specific
  liveStats?: LiveStreamStats;
  
  // Accessibility
  hasSubtitles: boolean;
  hasClosedCaptions: boolean;
  audioDescription?: boolean;
  
  // Quality & Safety
  contentRating: 'G' | 'PG' | 'PG-13' | 'R' | 'NC-17' | 'NR';
  factChecked: boolean;
  factCheckStatus?: 'verified' | 'disputed' | 'false' | 'misleading';
  moderationFlags: string[];
  
  // Personalization
  personalizedScore?: number;
  recommendationReason?: string;
  userInteractions?: UserVideoInteraction[];
}

export interface VideoCaption {
  language: string;
  url: string;
  format: 'srt' | 'vtt' | 'ttml';
  isAutoGenerated: boolean;
}

export interface LiveStreamStats {
  currentViewers: number;
  peakViewers: number;
  liveDuration: number;
  chatMessages: number;
  streamHealth: 'excellent' | 'good' | 'fair' | 'poor';
  bitrate: number;
  resolution: string;
  fps: number;
}

export interface UserVideoInteraction {
  userId: string;
  type: 'view' | 'like' | 'dislike' | 'comment' | 'share' | 'save' | 'report';
  timestamp: Date;
  duration?: number; // For view interactions
  progress?: number; // Percentage watched
}

export interface VideoFilter {
  platforms?: string[];
  categories?: string[];
  languages?: string[];
  duration?: {
    min?: number;
    max?: number;
  };
  uploadDate?: {
    from?: Date;
    to?: Date;
  };
  location?: string;
  contentRating?: string[];
  hasSubtitles?: boolean;
  isLive?: boolean;
  minViews?: number;
  sortBy?: 'relevance' | 'date' | 'views' | 'engagement' | 'duration' | 'trending';
  sortOrder?: 'asc' | 'desc';
}

export interface VideoSearchQuery {
  query: string;
  filters: VideoFilter;
  limit: number;
  offset: number;
  includeTranscriptions?: boolean;
  includeSuggestions?: boolean;
}

export interface VideoSearchResult {
  videos: WorldClassVideo[];
  totalCount: number;
  hasMore: boolean;
  nextOffset: number;
  suggestions?: string[];
  facets?: {
    platforms: { [key: string]: number };
    categories: { [key: string]: number };
    languages: { [key: string]: number };
  };
  searchTime: number;
}

export interface VideoReaction {
  id: string;
  videoId: string;
  userId: string;
  type: '👍' | '❤️' | '😂' | '😢' | '😡' | '😮' | '🔥' | '💯';
  timestamp: Date;
}

export interface VideoComment {
  id: string;
  videoId: string;
  userId: string;
  username: string;
  userAvatar: string;
  content: string;
  timestamp: Date;
  likes: number;
  replies: VideoCommentReply[];
  isEdited: boolean;
  isPinned: boolean;
  isModerator: boolean;
  isCreator: boolean;
}

export interface VideoCommentReply {
  id: string;
  userId: string;
  username: string;
  userAvatar: string;
  content: string;
  timestamp: Date;
  likes: number;
  isEdited: boolean;
}

export interface AdminDashboardData {
  // Source health monitoring
  sourceHealth: {
    [platform: string]: {
      status: 'online' | 'degraded' | 'offline';
      uptime: number;
      lastCheck: Date;
      errorCount: number;
      avgResponseTime: number;
    };
  };
  
  // Cache statistics
  cacheStats: {
    hitRate: number;
    totalRequests: number;
    totalHits: number;
    memoryUsage: number;
    avgResponseTime: number;
  };
  
  // User engagement metrics
  userEngagement: {
    totalUsers: number;
    activeUsers: number;
    avgSessionDuration: number;
    topInteractions: { type: string; count: number }[];
    engagementRate: number;
  };
  
  // Trending content
  trending: {
    videos: WorldClassVideo[];
    topics: { name: string; count: number; growth: number }[];
    hashtags: { tag: string; count: number; sentiment: number }[];
  };
  
  // System performance
  performance: {
    avgLoadTime: number;
    errorRate: number;
    apiLatency: number;
    bandwidthUsage: number;
  };
}

export interface I18nContent {
  en: {
    [key: string]: string;
  };
  es: {
    [key: string]: string;
  };
  pt: {
    [key: string]: string;
  };
}

export interface PersonalizationSettings {
  userId: string;
  preferences: {
    platforms: string[];
    categories: string[];
    languages: string[];
    contentTypes: string[];
  };
  behaviorData: {
    watchHistory: string[];
    likedVideos: string[];
    searchHistory: string[];
    interactionPatterns: { [type: string]: number };
  };
  aiInsights: {
    topicAffinities: { [topic: string]: number };
    engagementPredictions: { [videoId: string]: number };
    recommendationFeedback: { [videoId: string]: 'positive' | 'negative' | 'neutral' };
  };
}